
version: '3'
services:
  site:
    depends_on:
      - db
    volumes:
      - ../app:/var/www/html/med4share
      - ../apache2:/etc/apache2/sites-enabled
      - ./tmp:/tmp
    build: .
    container_name: site
    ports:
      - 80:80
    links:
      - db
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.21
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sort_buffer_size=512K
    ports:
      - 3306:3306
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: med4share
      MYSQL_ROOT_PASSWORD: 123